"""Change budget field to string for Client model

Revision ID: cca62c1d0fcd
Revises: 472efec970b3
Create Date: 2025-05-11 14:54:04.167759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca62c1d0fcd'
down_revision = '472efec970b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
